class PrimaryDBConf:
    sqlite_db_path = "edge/database/sqlite/primary.db"
    sqlite_schema_path = "edge/database/schema/primary.sql"

class SecurityDBConf:
    sqlite_schema_path_core = "edge/database/schema/security_core.sql" #the schema layout for dataset generated by Cockatoo Core
    sqlite_schema_path_generic = "edge/database/schema/security_generic.sql" #the schema layout for a generic txt dataset split by newlines

    sqlite_db_path_core = "edge/database/sqlite/security_core.db" #database for datasets generated by Cockatoo Core
    sqlite_db_path_generic = "edge/database/sqlite/security_generic.db" #database for generic txt datasets

class MetadataDBConf:
    sqlite_db_path = "edge/database/sqlite/metadata.db"
    sqlite_schema_path = "edge/database/schema/metadata_tracker.sql"