class PrimaryDBConf:
    sqlite_db_path = "edge/database/sqlite/primary.db"
    sqlite_schema_path = "edge/database/schema/primary.sql"

class SecurityDBConf:
    sqlite_schema_path_core = "edge/database/schema/security_core.sql" #the schema layout for dataset generated by Cockatoo Core
    sqlite_schema_path_generic = "edge/database/schema/security_generic.sql" #the schema layout for a generic txt dataset split by newlines

    # db path will be dynamically adjusted based on the dataset repository on GitHub.